### ISSUE TITLE
Vertical scroll bar on some mobile devices

### ISSUE THREAD

**Issue by EatTheRichTextFormat** [MKorostoff/1-pixel-wealth#16]
On my Moto G4 on Firefox, with window.innerWidth, window.innerHeight = 360, 512, the content doesn't fit on the screen and there's a vertical scroll bar. `body { overflow-y: hidden }` removes the scroll bar, but cuts off the bottom of the page, while `body { transform: scale(0.9); transform-origin: 0 0;}` works, but breaks the wealth counter.

**Comment by MKorostoff** [comment]
I've decided this is an acceptable behavior for the fraction of devices small enough to produce it.
