### ISSUE TITLE
Licensing info

### ISSUE THREAD

**Issue by lurnid** [MKorostoff/1-pixel-wealth#17]
Great work!
I'm talking to a colleague in higher ed about ideas to use this as an instructional tool, which might need it to be adapted in certain ways (e.g. adding citations to support the data presented). Are you happy for your work to be reused and adapted? Is there any particular license that you're planning to apply to it?

**Comment by MKorostoff** [comment]
Definitely GPL3 https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

I'll add a licence.txt file eventually

**Comment by MKorostoff** [comment]
License file added in 6b3d80e
