### ISSUE TITLE
Congratulations, not really an issue but..

### ISSUE THREAD

**Issue by Miguel349** [MKorostoff/1-pixel-wealth#23]
This is the best graph I have ever seen ilustrating one of the biggest problems in the world. If you have a donation account, I'd love to send you a dollar or two.. THANK YOU, I've been trying to explain this for a while and people just don't understand, because our minds aren't capable of understanding.

Anyway, I'd like to do the same with Amancio Ortega and Spain, is there any way I can create my own graph customizing the values and the texts? 

Thanks, :). 

Miguel.

**Comment by MKorostoff** [comment]
1. If you'd like to donate in support of the issues on this site, consider making a contribution to the [Against Malaria Foundation](https://www.againstmalaria.com/), which is my favorite charity.
2. If you wish to make a translation or alternate version, [see instructions here](https://github.com/MKorostoff/1-pixel-wealth/issues/8#issuecomment-622964168).
