### ISSUE TITLE
Improve instructions on opening screen

### ISSUE THREAD

**Issue by eliotb** [MKorostoff/1-pixel-wealth#27]
I watched someone who is used to a computer struggle to understand what was required with the side-scrolling.   

Opening screen needs something more explicit like:
"This page is VERY wide - Use the right arrow button or horizontal scroll bar to scroll this screen sideways"

**Comment by MKorostoff** [comment]
duplicate https://github.com/MKorostoff/1-pixel-wealth/issues/11
