### ISSUE TITLE
Please do a follow up for how 0.0001% could pay for COVID19 measures

### ISSUE THREAD

**Issue by davidosullivan** [MKorostoff/1-pixel-wealth#30]
Hey, 

Well done for this, I think its an extraordinarily poignant way of showing people (around the world) wealth inequalities.

I'd like to suggest a sequel.

'How the richest 0.01% could wipe out the debts incurred by global governments as a result of COVID19'

Perhaps you could show how globally, the top few people in each country could give up 30-40% of their astronomical wealth to pay for the measures that governments have taken to support the population during the COVID19 pandemic, and that rather than this taking generations to pay off, the richest 0.01% could give up just 40% of their wealth (and still be billionaires afterwards) and the whole situation could be solved (financially anyway)

I've no idea if thats actually possible, maybe the sums that have been spent are too great, but if they are not, it would be great to see it displayed in the same kind of way you did '1 pixel wealth'

Anyway, great work :)

**Comment by MKorostoff** [comment]
I've given some thought to making an international version of this, actually. The thing holding me back, besides the time commitment, is the question of what it even means to be "rich" in the global context. You can be rich by local standards, but poor in a global context, and vice versa. Purchasing power, tax policy, inequality, and property ownership vary all over the world. Moreover, I don't know which wealth to count. Would I include the wealth of royalty? The wealth of state owned enterprises? The wealth of organized crime? Wealth hidden in the Cayman islands? And even if we could resolve the philosophical questions, we still run into the problem that this data is just not available for most countries.

So, I doubt I'll ever get around to making a global version of this. However, a number of people have created forks of this repo to build visualizations of inequality in their own countries. If you'd like to do the same for the global perspective, go for it.
