### ISSUE TITLE
Be more precise using global variables.

### ISSUE THREAD

**Issue by Eddie7mail** [MKorostoff/1-pixel-wealth#46]
Hey, great job! It's really impressive to see it going, literally, on your face.

I would like to ask you to be more precise on your statistical, and "compare apples to apples".
This wealth is not made upon North American bids or it's people sacrifice only. It's coming from all around the world, so, why not to compare the data with global information, for instance: what would be the cost to provide a home for worldwide homeless veterans? Or to test everyone for coronavirus?

I agree with "We cannot accept this level of inequality any longer." So, is there an option?

**Comment by MKorostoff** [comment]
duplicate #30
