### ISSUE TITLE
Add Dutch translation to list

### ISSUE THREAD

**Issue by jobveldhuis** [MKorostoff/1-pixel-wealth#49]
Hey there, I have gone ahead and worked on a Dutch translation which can be found [here](https://jobveldhuis.github.io/1-pixel-weelde/): `https://jobveldhuis.github.io/1-pixel-weelde/`

**Comment by MKorostoff** [comment]
Awesome! I'll update the list soon. Thank you for making this.

**Comment by MKorostoff** [comment]
Added in b4b18e8. Thanks again!
