### ISSUE TITLE
Doesn't scroll past 3.5 bln USD

### ISSUE THREAD

**Issue by SjoerdB93** [MKorostoff/1-pixel-wealth#52]
Hey,

I am not sure if you're reading this, but it doesn't scroll past 3.5 bln USD. I tried in Firefox and Chrome on my desktop (Linux Fedora), and on my mobile phone (iPhone). I swear it went to like 100 bln USD before, but maybe I was wrong?

Sjoerd

**Comment by MKorostoff** [comment]
@SjoerdB93 can you clarify what you mean by "it doesn't scroll past"? Do you mean the little number counter at the bottom left? Or do you mean that you attempt to swipe and the browser just sits there and doesn't do anything. I was able to scroll all the way to the end of both the bezos counter and the 400 people counter:

<img width="725" alt="scroll" src="https://user-images.githubusercontent.com/1197335/91577151-51d9c500-e916-11ea-9b14-77350c6a466c.png">

<img width="725" alt="end" src="https://user-images.githubusercontent.com/1197335/91577161-556d4c00-e916-11ea-991c-34bfbbc20185.png">

Did you maybe grab the scrollbar, and skip all the way to the end, and then mistake the actual final number (3.5 _trillion_) for 3.5 billion?

**Comment by SjoerdB93** [comment]
> Did you maybe grab the scrollbar, and skip all the way to the end, and then mistake the actual final number (3.5 trillion) for 3.5 billion?

Ha thanks, I sure feel stupid now. That's exactly what happened!
