### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by johnbent** [MKorostoff/1-pixel-wealth#53]
I don’t have an Issue. Well, I guess my issue is that this egregiously poor distribution of wealth is immensely destructive of the society that we should have. That we deserve.  

So, just wanted to say that I appreciate the really good work you are doing help us get where we need to go. 

Please close this Issue but please also keep fighting the good fight!

**Comment by MKorostoff** [comment]
Thanks! Glad you enjoyed.
