### ISSUE TITLE
Italian adaptation

### ISSUE THREAD

**Issue by giacomoortona** [MKorostoff/1-pixel-wealth#56]
Hi,

Thank you for creating this site!
I created an Italian version of it at this address:
https://giacomoortona.github.io/1-pixel-wealth/
It is not a mere translation, since I changed the data and examples to fit the Italian case (G. Ferrero instead of Bezos, 40 billionaires instead of 400, different examples etc.)
I hope you have no objections if I make it public.
I made sure to mention the original website at the beginning and at the end, but please let me know if you think I should modify the adaptation.

**Comment by MKorostoff** [comment]
Looks great! I added a link to it in the readme file. You can do anything you want with this code, you don't need my permission and you don't need to meet any particular set of content standards. The only thing you _do_ need to do is [make it open source](https://github.com/MKorostoff/1-pixel-wealth/blob/master/LICENSE.txt) (which just means making your github repository public).
