### ISSUE TITLE
Y-overflow on small devices

### ISSUE THREAD

**Issue by mantagen** [MKorostoff/1-pixel-wealth#58]
Absolutely love this project.

You've likely got the stats on how many of your visitors are using which screen sizes, but on my phone (iphone SE 1st generation), there's y-overflow which slightly ruins the effectiveness of the layout.

**Comment by MKorostoff** [comment]
Thank you for the bug report, but I have concluded this is acceptable for the fraction of devices small enough to produce it. Reported previously in #16
