### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by timmc** [MKorostoff/1-pixel-wealth#59]
My fingers got pretty tired doing all that scrolling. While that kind of helped drive home the point, I almost gave up a few times, and I know someone who did. Would you consider adding an autoscroll button (maybe with a key binding) that scrolls to the next entry?

**Comment by Arnauw** [comment]
I agree, this is a good idea.

**Comment by MKorostoff** [comment]
Thank you for the suggestion, this was previously requested in #4, where I provided the following explanation.

> I actually built this feature at one point. It was hella complex and really cool, with an 'autopilot' feature, that would pause at each info section, or allow you to manually click a next/previous navigation to advance just one item at a time. It ends up being a really tricky feature, because A) different sections require different scroll/pause behaviors depending on if they're sticky and B) there are a ton of edge cases to anticipate regarding people who use a mixture of autoscroll, next/prev, and natural scrolling, people who scroll backwards, people who reload mid scroll, people who scroll items only partially into view, etc. I got a thing that worked pretty well, but I just kept finding weird edge cases like if you scroll something partially into view, then reload, then use next/prev you'll be sent back to start (not a real example, just the sort of thing I kept running into). Also, I hated having floating buttons on the screen vying for the users attention when I want them to focus on the actual content. Ultimately, I just decided it was too much trouble for not enough benefit and that I was overcomplicating things.
