### ISSUE TITLE
A text which tells that it is the last one.

### ISSUE THREAD

**Issue by tarunkota** [MKorostoff/1-pixel-wealth#60]
The last text which a users sees is "We cannot accept this level of inequality any longer."  and the user continues to scroll. For a better user experience, it would be helpful if we end the article in a better way where the use gets to know that the article has completed.

**Comment by MKorostoff** [comment]
Thank you for the suggestion, but I prefer the current behavior

**Comment by JounQin** [comment]
I love the current behavior too, because I'm shocked when trying to scroll to next text, and I just found I can't, I have to use the scrollbar of the browser. It's such an amazing experience.
