### ISSUE TITLE
Potential error

### ISSUE THREAD

**Issue by Kylebrown9** [MKorostoff/1-pixel-wealth#61]
The value "0.39%" in the paid maternity and paternity leave info box seems like it should be an error based on context.
Is it supposed to "39%"?

https://github.com/MKorostoff/1-pixel-wealth/blob/master/index.html#L565

**Comment by MKorostoff** [comment]
<img width="396" alt="Screen Shot 2021-04-26 at 3 39 00 PM" src="https://user-images.githubusercontent.com/1197335/116140732-bf0c4880-a6a5-11eb-92c4-70d7e02509dd.png">

**Comment by Kylebrown9** [comment]
Apparently I read the sentence wrong and flipped the per year and overall numbers.
Sorry about that, looks fine.
