### ISSUE TITLE
Open to sponsorship?

### ISSUE THREAD

**Issue by tiagostutz** [MKorostoff/1-pixel-wealth#62]
Hey there @MKorostoff !
First of all, thanks for sharing your art with the world. 1-pixel-wealth is just so brillant, intense and profound. I took a breath at the beginning and just released it at the end.

I'd like to know if you have some sponsorship channel for me to donate and what do you think about enabling the GitHub Sponsorship button? I'd be really honored to contribute with this project here in GitHub.

**Comment by MKorostoff** [comment]
@tiagostutz thank you, I'm flattered, but I decided long ago that any attempt to monetize this project would dilute the message and give billionaire defenders an extra line of attack (see: [mister gotchya](https://thenib.com/mister-gotcha/)). I want to avoid distracting side conversations as much as possible and stay on message. Besides, there's no world in which this website ever brings in enough money to meaningfully change my lifestyle.

If you feel compelled to donate, consider giving to my favorite charity, the [against malaria fund](https://www.againstmalaria.com/).
