### ISSUE TITLE
Show what percentage each person would get were it evenly distributed.

### ISSUE THREAD

**Issue by lancelot2112** [MKorostoff/1-pixel-wealth#65]
Add squares in there to show what percentage each person would get were it equally distributed (hint.. around $600 for 200million americans).  So veterans could be housed if everyone donated $5 * 9 => $45 (two dinners) to a charity.  The issue isn't that there isn't enough money... the issue is that everyone wants to do different things.  THAT needs to be highlighted here.

Also show the accumulated totals of everything everybody wants to do with the money (not just cherry picked examples) and how we do not have enough money to cover everything.  It's easy when you as an individual have goals but when you take everybody's goals as a whole where should the money go?   

Also in order to liquidate these stocks somebody has to buy the stock.  That either comes from margin (individual people taking out loans) or people tying up savings into the stock market.  It'd be a way to redistribute the stock however the same could be accomplished again if individuals just donated a small portion of their own money to accomplish the same goals.  We should be advocating for individuals taking a responsibility to donate to the things they believe are important and or pruning the things we are doing to be more focused.

**Comment by MKorostoff** [comment]
nah
