### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by seaque** [MKorostoff/1-pixel-wealth#67]
Hi, thanks for this site. [Here's my Turkish translation](https://seaque.github.io/1-pixel-wealth) of the original page, USA figures.

**Comment by siyahkedi** [comment]
I found this page like 2 weeks ago, and was planning to try working on a Turkish translation, but my Turkish is not as strong as I'd like it to be. So thank you for this!

**Comment by MKorostoff** [comment]
Thanks! Added link in b0c1040
