### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by adamklimowski** [MKorostoff/1-pixel-wealth#68]
https://github.com/adamklimowski/1-pixel-wealth/pull/1/commits/e33f47adb1d8a2d4ad7637fa079f62390500a1bd

**Comment by MKorostoff** [comment]
Thanks! I've added a link to your repository from the main project. Please also consider publishing your code with [Github Pages](https://pages.github.com/). This will allow visitors to view your page like any other website, without having to download the code to their computer first. Here is a video showing how to achieve this https://youtu.be/8hrJ4oN1u_8?t=347

**Comment by adamklimowski** [comment]
Thank you for your help :) I've published the page and it's now available here: https://adamklimowski.github.io/1-pixel-wealth/.

**Comment by MKorostoff** [comment]
@adamklimowski thanks! I have updated to link to point to the published version. great work!
