### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by Yzagzag** [MKorostoff/1-pixel-wealth#69]
its 39% not 0.39!!

Paid maternity and paternity leave are estimated to cost around $12 billion per year. This is 0.39% of the wealth controlled by 400 Americans. It is 5% of the wealth they accrued in 2020 alone.
If they repeated this payment every year for the next 100 years, it would equal 39% of the wealth they control today.

**Comment by MKorostoff** [comment]
No you've misread it
