### ISSUE TITLE
Translation/localisation for Austria/Europe

### ISSUE THREAD

**Issue by dominikgries** [MKorostoff/1-pixel-wealth#76]
Hi Matt,
just wanted to let you know that we created an Austrian adaptation of your site, that follows the general idea with Austrian numbers. Language is German: [vermoegen.moment.at](vermoegen.moment.at) 
We hope you appreciate it and we would be thrilled if you would add it to the list of adapations.

All the best from Vienna,
Dominik, Moment Magazine

**Comment by MKorostoff** [comment]
Added to readme, thanks! Looks great
