### ISSUE TITLE
Directing towards a resistant audience.

### ISSUE THREAD

**Issue by Neberheim** [MKorostoff/1-pixel-wealth#78]
I would ask that you consider removing the coronavirus vaccine visualization. Not for any scientific or public health reason, but because the audience who needs to see this the most is also the mostly likely to be resistance to covid science. I believe it’s a fallacy called “poisoning the well”. People will find any reason to protect a crumbling paradigm.

**Comment by MKorostoff** [comment]
This is an interesting suggestion, which I had not considered before. I took some time this morning to seriously consider it, but I have decided not to implement these changes. The people you're concerned about reaching are not reachable. If you show this website to someone who is already hostile to the message, they will always reject it, and there is no amount of softening or watering down the message that will change this.

This website is not for the ideologically committed, it is for people who are still open to persuasion and debate. You can take someone with no opinion, and persuade them to have an opinion. You can take someone with a weakly held opinion, and radicalize them into having a strong opinion. These are the people we should try to reach.
