### ISSUE TITLE
2022 update with Elon Musk

### ISSUE THREAD

**Issue by harry-wood** [MKorostoff/1-pixel-wealth#80]
Any plans to do a 2022 update to this? Nowadays Elon Musk has the highest net worth at US$265 billion. More pixels!

I notice it has been done here: https://engaging-data.com/how-rich-is-elon-musk/  I'm preferring your version without all the ads though

**Comment by MKorostoff** [comment]
Thanks for the suggestion, but I don't want to spend any more effort updating this. I think the central point ("the richest people have an incomprehensible amount of wealth") is made, and making it more precise or current doesn't fundamentally change the picture or the policy conclusions. Feel free to make a fork though.
