### ISSUE TITLE
endowment payout rule outdated link

### ISSUE THREAD

**Issue by Golova1111** [MKorostoff/1-pixel-wealth#81]
Hello, first of all, thanks for such an exciting project
I can't entirely agree with all the statements but for sure your job is great

One of the project links is outdated: [5% endowment payout rule](https://www.manning-napier.com/insights/blogs/insights-for-non-profits/endowments-and-foundations-a-closer-look-at-spending-rules). A possible alternative for it is e.g. https://www.pionline.com/article/20170508/ONLINE/170509926/endowments-should-rethink-the-5-rule

And IDK if it was asked before, what exactly are you thinking about [The Giving Pledge](https://en.wikipedia.org/wiki/The_Giving_Pledge) campaign? It sounds relatively close to your ideas, isn't it?

Thanks again for this project!

**Comment by MKorostoff** [comment]
thanks, will update, not sure if that link you suggested is quite right though. Re: the giving pledge, I think it's great, though it would be better if we had an economy that allowed workers to benefit from their own productivity more without having to rely on the charity of aristocrats.

**Comment by MKorostoff** [comment]
Fixed in [`8eec57c`](https://github.com/MKorostoff/1-pixel-wealth/commit/8eec57c346cd39645e1acaa4ea05dbb4f585e9a8). Thanks for the report.
