### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by pixelherodev** [MKorostoff/1-pixel-wealth#83]
https://www.who.int/water_sanitation_health/watandmacr3.pdf gives a 404.

**Comment by MKorostoff** [comment]
thanks, I'll find a suitable replacement

**Comment by pixelherodev** [comment]
No problem - didn't have time [or inclination] to find a replacement, so I figured letting you know was literally the least I could do.

I don't agree with _all_ of the politics in the site, but I think it's an extremely valuable resource nonetheless - thanks for making this! :)

**Comment by possiblynova** [comment]
archive.org likely has this archived

**Comment by fsologureng** [comment]
> [archive.org](archive.org) likely has this archived

This is the last one before the 404: https://web.archive.org/web/20220221195720/https://www.who.int/water_sanitation_health/watandmacr3.pdf

**Comment by MKorostoff** [comment]
fixed in 3ff05ac

Thanks @pixelherodev, @fsologureng, and @possiblynova!
