### ISSUE TITLE
Action Items

### ISSUE THREAD

**Issue by Rekunan** [MKorostoff/1-pixel-wealth#87]
You've gotten me all fired up and motivated. Now I wanna do something, but I have no idea what to do. Please list some action items like websites or whatever we can go to in order to help the situation.

**Comment by MKorostoff** [comment]
I understand the impulse behind this request, but I think it’s incorrect. When you end on a call to action, you leave the reader with hope that someone other than themself will answer the call. If you experience anger and hopelessness while viewing the site, then good; that is the appropriate emotional reaction to the world we actually live in. Hopelessness and disillusion make people receptive to change, but first they need to sit with those feelings, not engage in a tedious debate about tax policy.
